#ifndef DSR_EPISODIC_API_H
#define DSR_EPISODIC_API_H

#include <deque>
#include <dsr/core/topics/IDLGraphPubSubTypes.hpp>
#include <dsr/core/types/user_types.h>
#include <fstream>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "DSRDecoder.h"
#include "DSRTypeTrait.h"

namespace DSR {

    /**
     * @brief DSRData is the public data type returned by the EpisodicMemoryAPI.
     *
     *  K   → nodes, edges  (full snapshot)
     *  MN  → node_id, type, node_name, attributes
     *  MNA → node_id, attributes  (only the changed attributes)
     *  ME  → edge_from_id, edge_to_id, type, attributes
     *  MEA → edge_from_id, edge_to_id, type, attributes  
     *          (only the changed attributes) DN  → node_id DE  → edge_from_id, edge_to_id, type
     */
    struct DSRData {
        
        uint64_t timestamp;            ///< Nanosecond timestamp
        std::string modification_type; ///< "K", "MN", "MNA", "ME", "MEA", "DN", "DE"

        std::optional<uint64_t> node_id;                      ///< Node id  (MN, MNA, DN)
        std::optional<uint64_t> edge_from_id; ///< Edge source id  (ME, MEA, DE)
        std::optional<uint64_t> edge_to_id;   ///< Edge target id  (ME, MEA, DE)
        std::optional<std::string> type;      ///< Node/edge type
        std::optional<std::string> node_name; ///< Node name  (MN)

        std::map<std::string, DSR::Attribute> attributes; ///< Attributes (MN, MNA, ME, MEA)

        std::vector<DSR::Node> nodes; ///< Nodes list  (K only)
        std::vector<DSR::Edge> edges; ///< Edges list  (K only)
    };

    /**
     * @brief EpisodicMemoryAPI — query interface for historic DSR graph data.
     *
     * Indexes a recording file (produced by the episodic_memory agent) once on
     * construction and exposes read-only query methods that return DSRData
     objects.
    *
    * Usage:
    * @code
    *   DSR::EpisodicMemoryAPI api("keyframes_and_changes_3.txt");
    *   if (api.is_ready()) {
    *       auto kf = api.get_keyframe(0);
    *       auto changes = api.get_changes_between(t0, t1);
    *   }
    * @endcode
    */
    class EpisodicMemoryAPI {
    public:
        /**
         * @brief Constructor — indexes the given history file immediately.
         * @param filepath  Path to the history file generated by the agent.
         */
        explicit EpisodicMemoryAPI(const std::string &filepath);

        // -----------------------------------------------------------------------
        // Status
        // -----------------------------------------------------------------------

        /** @brief Returns true if the file was indexed successfully. */
        bool is_ready() const;

        /** @brief Returns the path of the currently indexed file. */
        const std::string &get_filepath() const;

        // -----------------------------------------------------------------------
        // Keyframe queries (global state snapshots)
        // -----------------------------------------------------------------------

        /** @brief Total number of keyframes in the file. */
        size_t get_keyframe_count() const;

        /**
         * @brief Timestamps (ns) of every keyframe, in file order.
         */
        std::vector<uint64_t> get_keyframe_timestamps() const;

        /**
         * @brief Timestamp of a specific keyframe by index.
         * @return nullopt if index is out of range.
         */
        std::optional<uint64_t> get_keyframe_timestamp(size_t keyframe_idx) const;

        /**
         * @brief Full keyframe (K event) at the given index.
         * @return DSRData with nodes and edges populated, or nullopt on error.
         */
        std::optional<DSRData> get_keyframe(size_t keyframe_idx);

        /**
         * @brief Keyframe whose timestamp is closest to and ≤ the given timestamp.
         *        If all keyframes are after the timestamp, returns the first one.
         * @return nullopt if there are no keyframes.
         */
        std::optional<DSRData> get_keyframe_at_time(uint64_t timestamp);

        /**
         * @brief Index of the keyframe whose timestamp is closest to and ≤ the given timestamp.
         *        If all keyframes are after the timestamp, returns 0.
         * @return Index (0-based), or nullopt if no keyframes exist.
         */
        std::optional<size_t> get_keyframe_index_at_time(uint64_t timestamp);

        /**
         * @brief Index of the event at exactly the given timestamp.
         * @return Index in the event list, or nullopt if no exact match found.
         */
        std::optional<size_t> get_event_index_at_timestamp(uint64_t timestamp);

        // -----------------------------------------------------------------------
        // Local-change queries (MN, MNA, ME, MEA, DN, DE)
        // -----------------------------------------------------------------------

        /**
         * @brief Number of local changes recorded after keyframe `keyframe_idx`.
         */
        size_t get_local_changes_count(size_t keyframe_idx) const;

        /**
         * @brief All local changes belonging to keyframe `keyframe_idx`, in order.
         */
        std::vector<DSRData> get_local_changes(size_t keyframe_idx);

        /**
         * @brief Single local change at position `change_idx` within
         `keyframe_idx`.
        * @return nullopt if indices are out of range.
        */
        std::optional<DSRData> get_local_change(size_t keyframe_idx, size_t change_idx);

        // -----------------------------------------------------------------------
        // Time-range queries
        // -----------------------------------------------------------------------

        /**
         * @brief All events (keyframes + local changes) whose timestamp falls in
         * [t_start, t_end]. Uses binary search for efficiency.
         */
        std::vector<DSRData> get_events_between(uint64_t t_start, uint64_t t_end);

        /**
         * @brief Only local-change events (no keyframes) in the time range
         * [t_start, t_end]. Uses binary search for efficiency.
         */
        std::vector<DSRData> get_changes_between(uint64_t t_start, uint64_t t_end);

        /**
         * @brief Event at exactly the given timestamp, or nullopt if not found.
         * Uses binary search.
         */
        std::optional<DSRData> get_event_at_timestamp(uint64_t timestamp);

        // -----------------------------------------------------------------------
        // Node-centric queries
        // -----------------------------------------------------------------------

        /**
         * @brief All events that reference a given node ID (MN, MNA, DN).
         *        Note: node IDs in the history file are the *original* IDs at
         *        recording time, NOT the DSR-assigned IDs in the live graph.
         */
        std::vector<DSRData> get_node_history(uint64_t node_id);

        /**
         * @brief All events that reference the node with the given name.
         *        Searches through MN events to match by node name.
         */
        std::vector<DSRData> get_node_history_by_name(const std::string
        &node_name);

        /**
         * @brief Changes to a node within a time range.
         *        Returns only local changes (MN, MNA, DN) not keyframes.
         */
        std::vector<DSRData> get_node_changes_between(uint64_t node_id,
                                                       uint64_t t_start,
                                                       uint64_t t_end);

        // -----------------------------------------------------------------------
        // Edge-centric queries
        // -----------------------------------------------------------------------

        /**
         * @brief All events that reference the edge (from_id → to_id) of the given
         * type.
         */
        std::vector<DSRData> get_edge_history(uint64_t from_id, uint64_t to_id,
                                                const std::string &edge_type);

        // -----------------------------------------------------------------------
        // Type-filtering queries
        // -----------------------------------------------------------------------

        /**
         * @brief All events of a specific modification type.
         * @param mod_type  One of: "K", "MN", "MNA", "ME", "MEA", "DN", "DE"
         */
        std::vector<DSRData> get_events_by_type(const std::string &mod_type);

        private:
        // -----------------------------------------------------------------------
        // Internal index entry
        // -----------------------------------------------------------------------

        struct EventMeta {
            uint64_t timestamp;
            std::streampos file_position;
            size_t line_length;
            std::string modification_type;
            size_t keyframe_index;
        };

        // -----------------------------------------------------------------------
        // State
        // -----------------------------------------------------------------------

        std::string filepath_;
        bool ready_ = false;

        std::vector<EventMeta> keyframe_meta_;
        std::map<size_t, std::vector<EventMeta>> local_changes_meta_;
        std::vector<EventMeta> all_events_meta_;

        // Index: node_name → vector of node IDs that had this name
        std::map<std::string, std::vector<uint64_t>> node_name_index_;

        // LRU cache  (timestamp → decoded event)
        static constexpr size_t CACHE_SIZE = 100;
        std::map<uint64_t, std::unique_ptr<DSREvent>> cache_;
        std::deque<uint64_t> cache_order_;

        // -----------------------------------------------------------------------
        // Private helpers
        // -----------------------------------------------------------------------

        bool index_file_();
        std::string read_line_at_(std::streampos pos) const;
        const DSREvent *get_event_(const EventMeta &meta);
        void evict_lru_();
        void touch_lru_(uint64_t timestamp);
        static DSRData to_dsr_data_(const DSREvent &ev);
        static std::pair<uint64_t, std::string>
        parse_header_(const std::string &line);
        size_t find_keyframe_index_at_time_(uint64_t ts) const;

        // Binary search helpers
        size_t find_first_event_by_time_(uint64_t t_start) const;
        size_t find_last_event_by_time_(uint64_t t_end) const;
    };

} // namespace DSR

#endif // DSR_EPISODIC_API_H